config/routes.rb
Rails.application.routes.draw do
  get 'photos/edit'

  get 'photos/index'

  get 'photos/new'

  get 'photos/show'

  get 'comments/edit'

  get 'comments/new'

  get 'albums/edit'

  get 'albums/index'

  get 'albums/new'

  get 'albums/show'

    devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root "albums#index"

	  resources :albums do 
	  	resources :photos do
	  		resources :comments
	  	end
	  end

end

app/models/album.rb
class Album < ApplicationRecord
	has_many :photos, dependent: :destroy 
	belongs_to :user

	mount_uploader :avatar, AvatarUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :album
	has_many :comments, dependent: :destroy

	mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :albums, dependent: :destroy
  has_many :comments, dependent: :destroy 
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
 
before_action :find_album, only: [:show, :edit, :update, :destroy]

	def index
		@albums = Album.all.order("created_at DESC")
	end

	def show
	end

	def new
		@album = current_user.albums.new
	end

	def create
		@album = current_user.albums.new(album_params)
		@album.user_id = current_user.id
		if @album.save
			redirect_to @album, notice: "Succesfully created."
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @album.update(album_params)
			redirect_to @album, notice: "Succesfully updated."
		else
			render 'edit'
		end
	end

	def destroy
		@album.destroy
		redirect_to root_path
	end

	private
	def album_params
		params.require(:album).permit(:title, :description, :avatar, :body, :user_id, :photo_id)
	end

	def find_album
		@album = Album.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  	before_action :find_album
	before_action :find_photo
	before_action :find_comment, only: [:edit, :update, :destroy]

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.photo_id = @photo.id
		@comment.user_id = current_user.id 

		if @comment.save
			redirect_to album_photo_path(@album, @photo)
		else
			render 'new'
		end
	end

	def edit 
	end

	def update
		if @comment.update(comment_params)
			redirect_to album_photo_path(@album, @photo)
		else 
			render 'edit'
		end
	end

	def destroy
		@comment.destroy 
		redirect_to album_photo_path(@album, @photo)
	end
	

	private
	def comment_params 
		params.require(:comment).permit(:body, :post_id, :user_id, :album_id)
	end

	def find_album
		@album = Album.find(params[:album_id])
	end

	def find_photo
		@photo = Photo.find(params[:photo_id])
	end

	def find_comment
		@comment = Comment.find(params[:id])
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :find_album 
	before_action :find_photo, only: [:show, :edit, :update, :destroy]


	def index
		@photos = Photo.where(:album_id => @album.id).order("created_at DESC")
	end

	def show
	
	end

	def new
		@photo = @album.photos.new
	end

	def create
    	@photo = Photo.new(photo_params)
		@photo.album_id = @album.id

		if @photo.save
			redirect_to album_path(@album), notice: "Succesfully posted."
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @photo.update(photo_params)
			redirect_to album_photo_path(@album, @photo), notice: "Succesfully updated."
		else
			
			render 'edit'
		end
	end
	


	def destroy
		@photo.destroy
		redirect_to root_path
	end

	private
	def photo_params
		params.require(:photo).permit(:title, :description, :avatar, :body, :album_id, :comment)
	end

	def find_album
		@album = Album.find(params[:album_id])
	end

	def find_photo
		@photo = Photo.find(params[:id])
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for @album, html: {multipart: true}, url: albums_path do |f|  %>
	<% if @album.errors.any? %>
		<div id="errors"> 
			<h2> <%= pluralize(@album.errors.count, "error") %> prevented this Photo from saving </h2> 
			<ul> <% @album.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	
	
	<%= f.input :title, input_html: {class:'form-control' }  %>
	<%= f.input :description, input_html: {class:'form-control' }  %>
	<%= f.file_field :avatar %>



	<%= f.button :submit, class: "btn btn-info" %>
<% end %>

app/views/albums/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>Edit Album</h1>

	<%= form_for @album, html: {multipart: true}, url: album_path do |f| %>


	<% if @album.errors.any? %>
		<div id="errors"> 
			<h2> <%= pluralize(@album.errors.count, "error") %> prevented this album from saving </h2> 
			<ul> <% @album.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


	  <p>
	    <%= f.label :title %><br>
	    <%= f.text_field :title %>
	  </p>
	 
	  <p>
	    <%= f.label :description %><br>
	    <%= f.text_area :description %>
	    <%= f.file_field :avatar %>
	  </p>
	 
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>
	<br>
	<br>

	<%= link_to 'Back', albums_path, class: 'btn btn-success btn-lg' %>

</div>

app/views/albums/index.html.erb
<h1>List of all Albums</h1>
 
<table class="table table-hover" id="myTable">
  
  <thead>
  <tr>
    <th >Title</th>
    <th>Creator</th>
    <th>Time Created</th>
  </tr>
  </thbook


 <tbody>
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.user.email %></td>
      <td><%= album.created_at.strftime("%d-%b-%Y, %l:%M%P") %></td>
      <td><%= image_tag(album.avatar.small_thumb.url, alt: 'Image') if album.avatar? %></td>

      <td><%= link_to 'View Album', album_path(album), class: 'btn btn-success btn-xs' %></td>
    </tr>
  <% end %>
  </tbody>

</table>

<br>
  <% if user_signed_in? %> 
      <%= link_to new_album_path, class: 'btn btn-warning' do %>
       <i class="glyphicon glyphicon-plus"></i> New Album
    <% end %>


<% end %>

app/views/albums/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">


				<h1>Add New Album</h1>

				<%= render 'form' %>
				

				<%= link_to 'Back', root_path %>

			</div>
		</div>
	</div>
</div>

app/views/albums/show.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="table-responsive">
	  <table class="table table table-hover">

		<h1><%= @album.title %></h1>

		    <thead>
		      <tr>
		      	<th>Album Title</th>
		        <th>Album Description</th>
		        <th>Created Date</th>
		      </tr>
		    </thead>


	

		    <tbody>
		      <tr>
		      	<td><%= @album.title %></td>
		        <td><%= @album.description %></td>
		        <td><%= @album.created_at.strftime("%d %b %Y %A, %I:%S %p") %></td>

		        <td> <button type="button" class="btn btn-info ">
					<%= link_to "View Photos", album_photos_path(@album.id) %> </button>
		        </td>

		      </tr>
		      <tr> 
		      <td><%= image_tag(@album.avatar.thumb.url, alt: 'Image', class: "photo") if @album.avatar? %></td>
		      	
		      </tr>
		    </tbody>
	  </table>
	</div>




		<button type="button" class="btn btn-info ">
			<%= link_to "Back", root_path %> 
		</button>
	<% if user_signed_in? %> 
		<% if @album.user_id == current_user.id %> 
		<button type="button" class="btn btn-warning ">
			<%= link_to "Add New Photo", new_album_photo_path(@album) %>
		</button>
		
		<button type="button" class="btn btn-warning">
			<%= link_to "Edit", edit_album_path(album_id: @album.id) %>
		</button>
		<button type="button" class="btn btn-warning">
			<%= link_to "Delete", album_path(album_id: @album.id), method: :delete,
  				data: {confirm: "Delete this Album?"}%>
		</button>
		<% end %>
	<% end %>
		<br>
	
</div>

app/views/comments/_comment.html.erb
<div class="comment">
	<h3> <em>Commented by: <%= comment.user.email %> </em></h3>
	<p class="comment-2"><%= comment.body %></p>

	<% if user_signed_in? %>
		<% if comment.user_id == current_user.id %>
			<div class="links btn-group">
				<%= link_to "Edit", edit_album_photo_comment_path(comment.photo.album, comment.photo, comment), class: 'btn btn-success' %>
				<%= link_to "Delete", album_photo_comment_path(comment.photo.album, comment.photo, comment), method: :delete, data: {confirm: "Are you sure?" }, class: 'btn btn-danger' %>
			</div>
			<br>
		<% end %>
	<% end %>
</div>

app/views/comments/edit.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="edit-review-form">
		<h1>Edit Comment</h1>
		<%= simple_form_for ([@album, @photo, @comment]) do |f| %>
			<%= f.input :body, label: Comment, input_html: {class:'form-control' }%>
			<%= f.button :submit, class: "btn btn-info" %>
		<% end %>
	</div>
</div>

app/views/comments/new.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="new-review-form">
		<h1>Comment</h1>
		<%= simple_form_for ([@album, @photo, @comment]) do |f| %>
			<%= f.input :body, label: Comment, input_html: {class:'form-control'} %>
			<%= f.button :submit, class: "btn btn-info"%>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/js/mdb.min.js">

  </head>



  <body>
<!-- navbar start --> 
   <div class="nav navbar navbar-inverse">
      <div class="container">
        <div class="navbar-brand"> 
          <%= link_to "Photo Album", root_path %> 
         </div>

            <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "New Album", new_album_path %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>

            <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Join", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>            
            </ul>
            <% end %>
        
      </div>
    </div>
<!-- navbar end --> 


<div class="container">
<!-- flash start --> 
  	<% flash.each do |name, msg| %>
  		<%= content_tag :div, msg, class: "alert alert-info"%>
  	 <% end %>
<!-- flash end --> 


<!-- yield start --> 
    <%= yield %>
<!-- yield start --> 
    </div>

  </body>

</html>

app/views/photos/edit.html.erb
<div class="edit_page col-md-8 col-md-offset-2">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Edit Photo</h1>
			</div>

			<div class="panel-body">
			 <div class="current_image">
				<strong class="center">Right now</strong><br>
					<%= link_to(image_tag(@photo.avatar.thumb.url, alt: 'Image', class: "photo"), @photo.avatar.url, target: '_blank') if @photo.avatar? %>
			</div>

			<!-- form start -->	
				<%= simple_form_for @photo, html: {multipart: true}, url: album_photo_path do |f|  %>
					<% if @photo.errors.any? %>
						<div id="errors">
							<h2> <%= pluralize(@photo.errors.count, "error") %> prevented this Photo from saving </h2>
							<ul> <% @photo.errors.full_messages.each do |msg| %>
								<li> <%= msg %></li>
								<% end %>
							</ul>
						</div>
					<% end %>



					<%= f.input :title, input_html: {class:'form-control' }  %>
					<%= f.input :description, input_html: {class:'form-control' }  %>


				<!-- START carrierwave photo upload via remote URL-->
				  <p>
				    <!--label>Photo URL:</label-->
				    <!--%= image_tag(@photo.avatar_url) if @photo.avatar? %-->
				    <!--%= f.text_field :remote_avatar_url %-->
						<%= f.file_field :avatar %>
				  </p>
				<!-- START carrierwave photo upload via remote URL-->


					<%= f.button :submit, class: "btn btn-info" %>
					<%= link_to "Cancel", album_photo_path(album_id: @album.id, id: @photo.id), class: "btn btn-warning" %> 

				<% end %>
			<!-- form end -->	


			</div>

			
		</div>
	</div>
</div>

app/views/photos/index.html.erb
<h1> <%= @album.title %> Album</h1>
	
<% @photos.each_slice(3) do |photos| %>
	<div class="row">
		<% photos.each do |photo| %>
			<div class="col-md-4">
				<%= link_to image_tag(photo.avatar.thumb.url, alt:'Photo', class: "photo"), album_photo_path(album_id: @album.id, id: photo.id) if photo.avatar? %>
			</div>
		<% end %>	
	</div>	
<% end %>


	
 

app/views/photos/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">


				<h1>Add New Photo</h1>

				<%= simple_form_for [@album, @album.photos.build], html: {multipart: true}, url: album_photos_path do |f|  %>
					<% if @photo.errors.any? %>
						<div id="errors">
							<h2> <%= pluralize(@photo.errors.count, "error") %> prevented this Photo from saving </h2>
							<ul> <% @photo.errors.full_messages.each do |msg| %>
								<li> <%= msg %></li>
								<% end %>
							</ul>
						</div>
					<% end %>


					<%= f.input :title, input_html: {class:'form-control' } %>
					<%= f.input :description, input_html: {class:'form-control' } %>
					<%= f.file_field :avatar %>
					<%= f.button :submit, class: "btn btn-info" %>

				<% end %>

				

				<%= link_to 'Back', root_path %>

			</div>
		</div>
	</div>
</div>

app/views/photos/show.html.erb
<h1> <%= @photo.title %> </h1>

<p><%= image_tag(@photo.avatar.thumb.url, alt: 'Image', class: "photo-show") if @photo.avatar? %></p>
<p> <%= @photo.description %></p>

<br><br>

		<button type="button" class="btn btn-info ">
			<%= link_to "Back", root_path %>
		</button>


		<% if user_signed_in? %> 
			<% if @album.user_id == current_user.id %> 
			<button type="button" class="btn btn-warning">
				<%= link_to "Edit", edit_album_photo_path(album_id: @album.id, id: @photo.id) %>
			</button>
			<button type="button" class="btn btn-warning">
				<%= link_to "Delete", album_photo_path(album_id: @album.id, id: @photo.id), method: :delete,
				data: {confirm: "Are you sure?"}%>
			</button>
			<% end %>
		<% end %>

<div> </div>

<div class="row">
	<div class="col-md-12">
		 
		 	<h1>All Comments</h1>
		 		
		 		<%= render @photo.comments %>
		 	<div>
		 	<%= link_to "Click to add a Comment", new_album_photo_comment_path(@album, @photo), class: "btn btn-default" %>
		 	</div>
	</div>
</div>